### PR TITLE
feat: added API functionality

### PR DESCRIPTION
**Pull request by xFuture603**
Hey @tuhlmann,

This is my first proposal for an API integration for this microservice. Using an API is optional, so the old way you can currently run locally still works. However, before I continue testing against our app and lint the code etc., I wanted your thoughts on the current implementation.

Here is a description of the new functions:

`fetch_all_container_images`: Retrieves all images currently stored in the API.

`fetch_image_versions`: Fetches all versions for a specific container image from the API.

`send_to_api`: Sends the updated tags for all images to the API using the POST /container-images endpoint.

`delete_container_image`: Deletes a specific container image or version from the API using its ID.

`compare_and_identify_deletions`: Compares the latest Docker Hub tags with the API-stored tags to identify outdated versions that need to be deleted.

Thanks in advance!

### CODE REVIEW

**Comment by tuhlmann** [comment]
@xFuture603 Can you please clarify you description and exactly state which functions run against Docker Hub and which against Symnix Backend?

We probably discussed that in the past, but please help me understand:

- How does the image scraper know which images it should query Docker for?
    - Do you configure a list of images somewhere outside of Symnix BE or does the list of templates in the Symnix DB inform the image scraper what information to get from Docket Hub?

**Comment by xFuture603** [comment]
> @xFuture603 Can you please clarify you description and exactly state which functions run against Docker Hub and which against Symnix Backend?
> 
> We probably discussed that in the past, but please help me understand:
> 
> * How does the image scraper know which images it should query Docker for?
>   
>   * Do you configure a list of images somewhere outside of Symnix BE or does the list of templates in the Symnix DB inform the image scraper what information to get from Docket Hub?

First I want to answer the general questions.

You have a `services.json` file where you maintain all the services that you want to scrape, according to the `README.md`: https://github.com/symnixhq/symnix-image-scraper?tab=readme-ov-file#%EF%B8%8F-usage

So to say, you configure a list of images outside of our Symnix BE. This way you can use the scraper for other use cases.

Now a little more about the functions:

### Functions Interacting with Docker Hub

These functions fetch data directly from the Docker Hub registry:

1. **`get_docker_image_tags(image)`**
   - Determines whether to call `get_docker_image_tags_official_repo` or `get_docker_image_tags_specific_repo`.
   - Ultimately retrieves tags from Docker Hub.

2. **`get_docker_image_tags_official_repo(image)`**
   - Fetches tags for an official Docker Hub repository using:
     ```
     https://registry.hub.docker.com/v2/repositories/library/{image}/tags?page_size=1000
     ```

3. **`get_docker_image_tags_specific_repo(username, repo_name)`**
   - Fetches tags for a user-specific repository using:
     ```
     https://registry.hub.docker.com/v2/repositories/{username}/{repo_name}/tags?page_size=1000
     ```

4. **`_fetch_and_parse_tags(url)`**
   - Makes HTTP requests to Docker Hub's API, handles pagination, and extracts tag names.

---

### Functions Interacting with the API

These functions interact with the custom API (defined by `API_URL` and authenticated via `API_TOKEN`):

1. **`fetch_all_container_images()`**
   - Fetches all container images from the API:
     ```
     GET {API_URL}/container-images
     ```

2. **`fetch_image_versions(image_name)`**
   - Retrieves all versions of a specific image from the API:
     ```
     GET {API_URL}/container-image-versions/{image_name}
     ```

3. **`send_to_api(updated_tags)`**
   - Sends updated image tags to the API:
     ```
     POST {API_URL}/container-images
     ```

4. **`delete_container_image(image_id)`**
   - Deletes a container image by ID using the API:
     ```
     DELETE {API_URL}/container-images/{image_id}
     ```

5. **`compare_and_identify_deletions(image_name, latest_tags, api_tags)`**
   - Compares tags fetched from Docker Hub with those in the API (via `fetch_image_versions`) to identify outdated tags.

---

Does that help you with a review @tuhlmann?

**Comment by tuhlmann** [comment]
@xFuture603 Thanks for the thorough explanation! Make sure and add this to BookStack to not loose it!

I would think you should go ahead and implement what you have in mind and then we look over it together and adapt. The container image api has not been tested yet and there are probably issues with it. It's good to have a tool to develop against and test both together.

**Review by tuhlmann — APPROVED** [review]

**Comment by xFuture603** [comment]
> @xFuture603 Thanks for the thorough explanation! Make sure and add this to BookStack to not loose it!
> 
> I would think you should go ahead and implement what you have in mind and then we look over it together and adapt. The container image api has not been tested yet and there are probably issues with it. It's good to have a tool to develop against and test both together.

I will document this in our knowledge base. Also I will merge this pull request for now and start to implement this microservice in our own infrastructure.

**Pull request merged**
